### ISSUE TITLE
masking error in slaterpbc during VMC

### ISSUE THREAD

**Issue by willwheelera** [WagnerGroup/pyqmc#136]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1000 but corresponding boolean dimension is 47563810862832

Error message:

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function apply at 0x2b4222f0be60>, <function vmc at 0x2b4235b7a710>, (<class 'tuple'>, [<pyqmc.slaterpbc.PySCFSlaterPBC object at 0x2b423b930c50>, <pyqmc.coord.PeriodicConfigs object at 0x2b423bc71b50>]), {'nsteps': 50, 'accumulators': {'energy': <pyqmc.accumulators.EnergyAccumulator object at 0x2b423bc74050>}, 'stepoffset': 150}))
kwargs:    {}  
Exception: IndexError('boolean index did not match indexed array along dimension 0; dimension is 1000 but corresponding boolean dimension is 47563810862832')

Traceback (most recent call last):
  File "hfvmc.py", line 67, in <module>
    wf, configs, nsteps=4000, nsteps_per=50, accumulators={"energy": enacc}, hdf_file=hdf_file, verbose=True, client=client, 
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/dasktools.py", line 68, in distvmc
    res = r.result()
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/distributed/client.py", line 221, in result
    six.reraise(*result)
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/dask/compatibility.py", line 107, in apply
    return func(*args, **kwargs)
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/mc.py", line 170, in vmc 
    ratio = np.multiply(wf.testvalue(e, newcoorde) ** 2, t_prob)
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py", line 239, in testvalue
    aos = self.evaluate_orbitals(epos, mask)
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py", line 142, in evaluate_orbitals
    mycoords = mycoords[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1000 but corresponding boolean dimension is 47563810862832

**Comment by lkwagner** [comment]
We need the input file that led to this and some description of how it happened, otherwise it is irreproducible and the issue will be closed.

**Comment by willwheelera** [comment]
This issue seems to be resolved by reducing the number of configurations. Maybe it was related to memory.
