### ISSUE TITLE
singular matrix error in distvmc with slaterpbc 

### ISSUE THREAD

**Issue by willwheelera** [WagnerGroup/pyqmc#137]
I ran VMC with dask (distvmc) using a HF slater determinant (PySCFSlaterPBC) with BFD ecps for 8 He atoms. An error was raised trying to invert a singular matrix, which followed division by zero warnings in the gradient and laplacian functions. Probably the wf was zero for the initial configuration, so determinant updates didn't work.

Running the attached file hfvmc_bug.py on the campus cluster with 20 processors resulted in the following error (full output file attached as well).

/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py:269: RuntimeWarning: divide by zero encountered in true_divide
  return ratios / testvalue
/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py:269: RuntimeWarning: invalid value encountered in true_divide
  return ratios / testvalue
/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py:256: RuntimeWarning: divide by zero encountered in true_divide
  return ratios[1:] / ratios[:1]
/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py:256: RuntimeWarning: invalid value encountered in true_divide
  return ratios[1:] / ratios[:1]
/projects/wagner/wawheel2/code/pyqmc/pyqmc/mc.py:85: RuntimeWarning: invalid value encountered in greater
  mask = tot > cutoff
/projects/wagner/wawheel2/code/pyqmc/pyqmc/mc.py:86: RuntimeWarning: invalid value encountered in true_divide
  g[mask, :] = cutoff * g[mask, :] / tot[mask, np.newaxis]
/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/numpy/core/_methods.py:75: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function apply at 0x2ba25ae07e60>, <function vmc at 0x2ba26d6bc440>, (<class 'tuple'>, [<pyqmc.slaterpbc.PySCFSlaterPBC object at 0x2ba293a44b50>, <pyqmc.coord.PeriodicConfigs object at 0x2ba29451fa10>]), {'nsteps': 50, 'accumulators': {'energy': <pyqmc.accumulators.EnergyAccumulator object at 0x2ba294522090>}, 'stepoffset': 50}))
kwargs:    {}  
Exception: LinAlgError('Singular matrix')

Traceback (most recent call last):
  File "hfvmc_bug.py", line 56, in <module>
    client=client, nsteps_per=50,
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/dasktools.py", line 68, in distvmc
    res = r.result()
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/distributed/client.py", line 221, in result
    six.reraise(*result)
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/dask/compatibility.py", line 107, in apply
    return func(*args, **kwargs)
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/mc.py", line 151, in vmc
    wf.recompute(configs)
  File "/projects/wagner/wawheel2/code/pyqmc/pyqmc/slaterpbc.py", line 177, in recompute
    self._inverse.append(np.linalg.inv(mo))
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 532, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/projects/wagner/anaconda3/envs/pyscf/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix

[hfvmc_bug.py.txt](https://github.com/WagnerGroup/pyqmc/files/4188851/hfvmc_bug.py.txt)
[output.txt](https://github.com/WagnerGroup/pyqmc/files/4188852/output.txt)

**Comment by willwheelera** [comment]
The problem was caused by calling wf.recompute on a configuration where the wf values was near zero. Fixing initial_guess resolved the problem, so I'm closing the issue.
