### ISSUE TITLE
Two examples are no longer running.

### ISSUE THREAD

**Issue by bbusemeyer** [WagnerGroup/pyqmc#84]
When running the examples, `cvmc_h2.py` and `parsl_h20.py` an error is raised: 

```
Traceback (most recent call last):
  File "cvmc_h2.py", line 111, in <module>
    sys["wf"], configs, accumulators={}, nsteps=40, nsteps_per=40, npartitions=ncore
  File "/mnt/home/bbusemeyer/programs/pyqmc/pyqmc/parsltools.py", line 64, in distvmc
    coord = np.split(coords, npartitions)
  File "/cm/shared/sw/pkg/devel/python3/3.7.3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 846, in split
    N = ary.shape[axis]
AttributeError: 'OpenConfigs' object has no attribute 'shape'
```

**Comment by bbusemeyer** [comment]
Looks to me like `parsltools` is not configured to work with `OpenConfigs` yet.

**Comment by lkwagner** [comment]
I would recommend you use `dask;` we've found that works better.

**Comment by lkwagner** [comment]
This should be fixed now.
